FROM apache/airflow:2.10.4-python3.11

USER root

RUN apt-get update && \
    apt-get install -y openjdk-17-jdk postgresql-client wget curl tar && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

ENV JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
ENV SPARK_VERSION=3.5.0
ENV SPARK_HOME=/opt/spark
ENV PATH=$PATH:$SPARK_HOME/bin

RUN curl -L https://archive.apache.org/dist/spark/spark-${SPARK_VERSION}/spark-${SPARK_VERSION}-bin-hadoop3.tgz \
    -o /tmp/spark.tgz && \
    tar -xzf /tmp/spark.tgz -C /opt && \
    mv /opt/spark-${SPARK_VERSION}-bin-hadoop3 ${SPARK_HOME} && \
    rm /tmp/spark.tgz

USER airflow

RUN pip install --no-cache-dir \
    "apache-airflow[postgres]==2.10.4" \
    apache-airflow-providers-apache-spark==4.11.0 \
    apache-airflow-providers-postgres==5.13.0 \
    pyspark==3.5.0 \
    psycopg2-binary \
    pandas \
    pyarrow \
    matplotlib \
    seaborn \
    scipy \
    rdkit \
    scikit-learn
