version: '3.8'
services:
  spark-master:
    image: apache/spark:latest
    container_name: spark-master
    ports:
      - '8080:8080'
      - '7077:7077'
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.master.Master
    hostname: spark-master
    networks:
      - spark-net

  spark-worker-1:
    image: apache/spark:latest
    container_name: spark-worker-1
    environment:
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
    depends_on:
      - spark-master
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    hostname: spark-worker-1
    networks:
      - spark-net

  spark-worker-2:
    image: apache/spark:latest
    container_name: spark-worker-2
    environment:
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
    depends_on:
      - spark-master
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    hostname: spark-worker-2
    networks:
      - spark-net

  spark-worker-3:
    image: apache/spark:latest
    container_name: spark-worker-3
    environment:
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
    depends_on:
      - spark-master
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    hostname: spark-worker-3
    networks:
      - spark-net

  airflow:
    build:
      context: .
      dockerfile: Dockerfile.airflow
    container_name: airflow-standalone
    environment:
      - AIRFLOW__CORE__EXECUTOR=SequentialExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://postgres:postgres@postgres:5432/airflow
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - _AIRFLOW_DB_MIGRATE=true
      - _AIRFLOW_WWW_USER_CREATE=true
      - _AIRFLOW_WWW_USER_USERNAME=admin
      - _AIRFLOW_WWW_USER_PASSWORD=admin
      - AIRFLOW_CONN_POSTGRES_DEFAULT=postgresql://postgres:postgres@postgres:5432/postgres
      - AIRFLOW_CONN_SPARK_DEFAULT=spark://spark-master:7077
      - SPARK_HOME=/opt/spark
      - JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64

    ports:
      - "8081:8080"
    command: bash -c "airflow db migrate && airflow users create --username admin --password admin --firstname Admin --lastname User --role Admin --email admin@example.com 2>/dev/null || true && airflow scheduler & airflow webserver -p 8080"
    depends_on:
      postgres:
        condition: service_healthy
      spark-master:
        condition: service_started
    volumes:
      - airflow_db:/opt/airflow
      - ./dags:/opt/airflow/dags
      - ./spark:/opt/airflow/dags/spark
      - spark_results:/tmp
    networks:
      - spark-net

  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    networks:
      - spark-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5


volumes:
  airflow_db:
  postgres_data:
  spark_results:

networks:
  spark-net:
    driver: bridge
